/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#060e20',
        'surface-dim': '#060e20',
        'surface-bright': '#1f2b49',
        'surface-variant': '#192540',
        'surface-container': '#0f1930',
        'surface-container-low': '#091328',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#141f38',
        'surface-container-highest': '#192540',
        'brand': '#1de1f1',
        'brand-dim': '#15b8c7',
        'brand-bright': '#5aeeff',
        'primary': '#1de1f1',
        'primary-dim': '#15b8c7',
        'primary-container': '#0d3d42',
        'primary-fixed': '#5aeeff',
        'primary-fixed-dim': '#1de1f1',
        'secondary': '#53ddfc',
        'secondary-dim': '#40ceed',
        'secondary-container': '#00687a',
        'secondary-fixed': '#65e1ff',
        'secondary-fixed-dim': '#48d4f3',
        'tertiary': '#699cff',
        'tertiary-dim': '#699cff',
        'tertiary-container': '#4388fd',
        'tertiary-fixed': '#8ab0ff',
        'tertiary-fixed-dim': '#73a2ff',
        'error': '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-surface': '#dee5ff',
        'on-surface-variant': '#a3aac4',
        'on-primary': '#39008c',
        'on-primary-fixed': '#000000',
        'on-secondary': '#004b58',
        'on-tertiary': '#001e4a',
        'on-error': '#490013',
        'outline': '#6d758c',
        'outline-variant': '#40485d',
        'background': '#060e20',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
      },
      animation: {
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease forwards',
      },
      keyframes: {
        'pulse-ring': {
          '0%': { transform: 'scale(0.33)' },
          '80%, 100%': { opacity: '0' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
