[features]
seeds = false
skip-lint = false

[programs.localnet]
agent_registry = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
a2a_market = "Market11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
